apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP_PLACEHOLDER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: APP_PLACEHOLDER
  template:
    metadata:
      labels:
        app: APP_PLACEHOLDER
    spec:
      containers:
      - name: APP_PLACEHOLDER
        image: IMAGE_PLACEHOLDER # Jenkins will replace this
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"